[package]
name = "bintool"
version = "0.1.0"
edition = "2021"

[dependencies]
getopts = "0.2"
regex = "1.10.2"
# rsa = "0.9.6"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.blxlib]
path = "../blxlib"
